#开奖时间
lotteryTime: '20:30'
#开奖前十分钟发送开奖提醒消息
notice: true
#最大可选数字
maxNumber: 20
#初始奖池
initialPrizePool: 500000.0
#奖池上限
maxPrizePool: 50000000.0
#每注金额
moneyPerBets: 200.0
#最大投注号码总量 0=无上限
maxNums: 0
#最大投注总量 0=无上限
maxBets: 0
#五等奖每注奖金  20选5中此奖概率：1/4
fifthPrize: 220.0
#五等奖奖金上限(每人)
#由于五等奖、四等奖、三等奖、特等奖的每注奖金是固定的 而不是像二等奖、一等奖那样按中奖注数平均分配
#这就可能导致有人中了低等奖但奖金比一等奖还多 例如有人中了一万注三等奖 而默认配置中三等奖每注奖金1万
#最后奖金就是10000*10000=1亿 是一等奖基础奖金的2倍 为了避免这种情况 可以设定每次开奖时 每人从五四三等奖获得的奖金上限
fifthPrizeMax: 500000.0
#四等奖每注奖金  20选5中此奖概率：1/19
fourthPrize: 800.0
#四等奖奖金上限(每人)
fourthPrizeMax: 1000000.0
#三等奖每注奖金  20选5中此奖概率：1/114
thirdPrize: 10000.0
#三等奖奖金上限(每人)
thirdPrizeMax: 3000000.0
#二等奖基础奖金 [二等奖每注奖金 = (25%奖池资金 + 基础奖金) / 中奖注数]  20选5中此奖概率：1/969
secondPrize: 5000000.0
#一等奖基础奖金 [一等奖每注奖金 = (75%奖池资金 + 基础奖金) / 中奖注数]  20选5中此奖概率：1/15504
firstPrize: 50000000.0
#特等奖每注奖金  20选5中此奖概率：1/1860480
specialPrize: 1234567890.0
#特等奖奖金上限(每人) 虽然感觉特等奖就是个摆设 但以防万一还是设置一个上限吧
specialPrizeMax: 12345678900.0
#奖池余额为0时是否继续发放五四三等奖
#在发奖时 五、四、三等奖的奖金会从奖池中扣除 所以如果有人中了大量三等奖 很可能导致奖池余额归零
#如果此项设为false 可能会导致部分中奖玩家无法领到奖金 降低游戏体验 如非必要不建议设为false
ignorePrizePool: true
#随机选号使用间隔(秒)
randomInterval: 30
#随机选号使用次数上限(每天)
randomMax: 3